### ISSUE TITLE
Add `pawn-package` tag search criteria 

### ISSUE THREAD

**Issue by BigETI** [Southclaws/pawndex#1]

**Comment by Southclaws** [comment]
I think I tried this initially but there was some reason why I didn't implement it... I'll try again anyway and report back.

**Comment by BigETI** [comment]
For my releases `pawn-list` and `pawn-map` it was easy to add a .gitattribute, however my plugin `pawn-memory` (which is a depency for both packages) can't be listed like that. Maybe if package requires package B, check if it is indexed and if not, index repository B. The best solution would be if it is a true PAWN package, it should be detectable with the `pawn-package` tag.

**Comment by Southclaws** [comment]
Update:

```
topic:pawn-package language:PAWN
```
Works fine, however it only returns 9 results because it's a logical AND operation

```
topic:pawn-package OR language:PAWN
```
I got:
> The search contains only logical operators (AND / OR / NOT) without any search terms.

So it seems I'll have to perform multiple requests...

**Comment by Southclaws** [comment]
Okay this should be resolved now, give it an hour to update and @ me if it's still not working.
